version: '3'

services:
  core_app:
    build: core_app/
    ports:
      - 9200:9200
    container_name: core_app
    depends_on:
      - bd_es

  get_data:
    build: get_data/
    ports:
      - 9200:9200
    container_name: get_data
    depends_on:
      - bd_es
  
  web_app:
    build: web_app/
    ports:
      - 9200:9200
      - 80:80
    container_name: web_app
    depends_on:
      - bd_es
      - get_data
      - core_app
  
  #Não teria de ser declarado primeiro, já que tem de subir primeiro?
  bd_es:
    build: bd_es/
    ports:
      - 9200:9200
    container_name: bd_es
    volumes:
      - esdata:/usr/share/elasticsearch/data

#Por que declara o volume novamente?
volumes:
  esdata: