version: '3'

services:
  app_core:
    build: app_core/
    ports:
      - 9200:9200
    container_name: app_core
    depends_on:
      - app_es_db

  app_get_data:
    build: app_get_data/
    ports:
      - 9200:9200
    container_name: app_get_data
    depends_on:
      - app_es_db
  
  app_web:
    build: app_web/
    ports:
      - 9200:9200
      - 80:80
    container_name: app_web
    depends_on:
      - app_es_db
      - app_get_data
      - app_core
  
  #Não teria de ser declarado primeiro, já que tem de subir primeiro?
  app_es_db:
    build: app_es_db/
    ports:
      - 9200:9200
    container_name: app_es_db
    volumes:
      - esdata:/usr/share/elasticsearch/data

#Por que declara o volume novamente?
volumes:
  esdata: